Winter fixes
UTDallasEPICS/Carson-s-Village pull request #112
Opened 2024-01-17 05:12 UTC by OfekShaltiel-UTD

Cleaned spacing, fixed cents issue in page editing, added admin functionality to page list (sees all pages), improved role based access with family concept, and added pagination to family reports table.

2024-01-30 06:03 UTC, pariahGH requested changes

2024-02-01 06:34 UTC, OfekShaltiel-UTD commented on pages/Page/[id].vue
> +    PageDonations: ref<PageDonation[]>([]).value,
I had an error when attempting to use a creation query with refs of array values being ``[]`` as part of the request body. However, I did fix it by using a destructure on the readbody(event).

2024-02-01 06:39 UTC, OfekShaltiel-UTD commented on server/api/family_page_list.get.ts
> +      User: {
I designed the page list to handle using both a family cuid and user cuid depending on several conditions.
Page list uses a user cuid / advocate from the header to load the advocates' familys' page, family cuid for families using the header, user cuid from the user list, and user cuid when an advocate creates a page (for their UX feedback of creating a page).

2024-02-01 06:42 UTC, OfekShaltiel-UTD commented on server/api/familiesReports.get.ts
> +    const [ count, families_raw, paginated_families  ] = await prisma.$transaction([
``paginated_families`` is a result of a ``page.findMany`` with pagination for use in the UI table, and the CSV uses families_raw which is not paginated.

2024-02-01 06:44 UTC, OfekShaltiel-UTD commented on pages/FamilyReports.vue
> +          const { data: familiesData } = await useFetch('/api/familiesReports', {
Let's meet to discuss this and other usages of ``useFetch``.

2024-02-07 02:15 UTC, OfekShaltiel-UTD commented on components/CVProgress.vue
> +console.log(actualBarWidth.value)
alright changed this.

2024-02-07 02:16 UTC, OfekShaltiel-UTD commented on pages/FamilyReports.vue
> +          const { data: familiesData } = await useFetch('/api/familiesReports', {
Let's make inappropriate usages of useFetch to be replaced by $fetch as a task for someone one the team to do.

2024-02-07 02:17 UTC, OfekShaltiel-UTD commented on server/api/family_page_list.get.ts
> +      User: {
Let's meet to redesign the page list.

2024-02-07 02:17 UTC, OfekShaltiel-UTD commented on server/api/page.post.ts
> +              cuid : userCuid || "0"
Alright changed this.

2024-03-05 02:59 UTC, OfekShaltiel-UTD commented on pages/Page/[id].vue
> +    PageDonations: ref<PageDonation[]>([]).value,
Alright fixed. I did not have any issues with using ``[]`` for these spots when testing the backend in these spots.

2024-03-07 21:15 UTC, closed without merging