created basic logic and code for family onboarding
UTDallasEPICS/Carson-s-Village pull request #87
Opened 2023-10-25 20:21 UTC by mshalom21

2023-10-25 20:24 UTC, pariahGH requested changes

2023-10-25 20:24 UTC, pariahGH commented on server/api/family_onboarding.ts
> +                return { success: true, message: "Already onboarded with Stripe." };
Instead of returning a value, redirect them back to their profile page

2023-10-25 20:24 UTC, pariahGH commented on server/api/family_onboarding.ts
> +import { PrismaClient } from "@prisma/client";
This file should be `family_onboarding.get.ts`

2023-11-06 21:28 UTC, mshalom21 commented
Hi Taz I was wondering if you could review the recent changes I made in the new commit. I am also working on integrating some new code that Ofek just finished working on

2023-11-08 04:07 UTC, pariahGH requested changes
If this is meant to take in a submitted foorm, it needs to be `family_onboarding.post.ts`, not a get and not with an _.

2023-11-13 03:53 UTC, pariahGH commented
Just to double check the flow here - the middleware checks if a stripe account exists, and if not redirects them to `family_onboarding.post.ts`, which then creates an account and redirects to onboarding?

if so, then it actually needs to be `family_onboarding.get.ts`, because a redirect won't be a POST request, and instead of getting the family id out of the request body we instead need to get it out of the query parameters - GET requests don't have a request body. we may be able to short circuit this a bit by doing the stripe account creation and redirecting in the middleware file itself instead of trying to redirect them twice in a row.

2023-11-15 22:14 UTC, closed without merging